server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.113.205.72:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 111
  redis:
    host: 47.113.205.72
    port: 6379
    password: 111
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
bloom-filter:
  expected-insertions: 1000000  # 期望插入的元素数量
  fpp: 0.01  # 误判率
snowflake-id:
  worker-id: 30
  datacenter-id: 30